name: On Merge
run-name: ${{ github.actor }} is running Build on ${{ github.head_ref }}, ${{ github.ref }}

on:
  push:
    branches:
      - main

concurrency: 'Merge-${{ github.event.number }}'

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set Git User Name and Email
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: |
          nx release version
          yarn ts-node ./scripts/nx-release.ts ${{ github.sha }}
